meta_product_name: "Help2Help"
meta_title: "Help2Help - We help you to help others and yourself"
meta_description: "Help is all around us all the time. We just have to know where to look for, call for and give. There's always someone out there who's been through what you've been through. Like us. Let's help each other!"
meta_image: "cover.png" # should exist in `app/assets/images/`
